name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set CFLAGS
        run: |
          $cflags = "-I$(Get-Location)\external\ffmpeg\include"
          echo "::set-env name=CFLAGS::$cflags"
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build-macos:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set CFLAGS
        run: |
          export INCLUDE_DIR="-I$PWD/external/ffmpeg/include"
          echo "::set-env name=CFLAGS::$INCLUDE_DIR"
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
