name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set CFLAGS
        run: |
          $includeDir = "$(Get-Location)\external\ffmpeg\include"
          echo $includeDir
          echo "::set-env name=CFLAGS::$includeDir"
      - run: echo $env:CFLAGS
  #    - name: Build
  #      run: cargo build --verbose
  #    - name: Run tests
  #      run: cargo test --verbose

  build-macos:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set CFLAGS
        run: |
          export INCLUDE_DIR="-I$PWD/external/ffmpeg/include"
          echo $INCLUDE_DIR
          echo "::set-env name=CFLAGS::$INCLUDE_DIR"
      - run: echo $CFLAGS
