name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Generate LFS file list
        run: git lfs ls-files -l | ForEach-Object { $_.split(" ")[0] } | Sort-Object > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id')}}-v1
      - name: Pull LFS files
        run: git lfs pull
      - name: Set CFLAGS
        run: |
          $cflags = "-I$(Get-Location)\external\ffmpeg\include"
          echo "CFLAGS=$cflags" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: .\scripts\package-win.ps1
      - uses: actions/upload-artifact@v2
        with:
          name: mlp-windows
          path: '*.zip'

  build-macos:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Generate LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id')}}-v1
      - name: Pull LFS files
        run: git lfs pull
      - uses: actions/checkout@v2
      - name: Set CFLAGS
        run: |
          export INCLUDE_DIR="-I$PWD/external/ffmpeg/include"
          echo "CFLAGS=$INCLUDE_DIR" >> $GITHUB_ENV
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: |
          chmod +x ./scripts/package-macos.sh
          ./scripts/package-macos.sh
      - uses: actions/upload-artifact@v2
        with:
          name: mlp-macos
          path: '*.tar.gz'
