name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set CFLAGS
        run: |
          $cflags = "-I$(Get-Location)\external\ffmpeg\include"
          echo "::set-env name=CFLAGS::$cflags"
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: .\scripts\package-win.ps1
      - uses: actions/upload-artifact@v2
        with:
          name: mlp-windows
          path: '*.zip'

  build-macos:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set CFLAGS
        run: |
          export INCLUDE_DIR="-I$PWD/external/ffmpeg/include"
          echo "::set-env name=CFLAGS::$INCLUDE_DIR"
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --release --verbose
      - name: Package
        run: |
          chmod +x ./scripts/package-macos.sh
          ./scripts/package-macos.sh
      - uses: actions/upload-artifact@v2
        with:
          name: mlp-macos
          path: '*.tar.gz'
